
[[redirects]]
  from = "/api/v1/*"
  to = "https://sedna.univ-fcomte.fr/jsp/custom/ufc/:splat"
  status = 200
  force = true # COMMENT: ensure that we always redirect

[build]
  base = "/"
  publish = "dist/"
  command = "npm run build"
